### ISSUE TITLE
Rename to chromaticore.github.io

### ISSUE THREAD

**Issue by RGBProductions** [chromaticore/chromaticore.github.io#1]
Rename this repository to chromaticore.github.io so users can input chromaticore.github.io instead of chromaticore.github.io/website

**Comment by Henderythmix** [comment]
Oh wait you can't do anything. can you? k I'll do it this time and I'll figure out how to fix it

**Comment by RGBProductions** [comment]
I think I could, but wasn't in a position to at the time I posted this
